### ISSUE TITLE
Go Badges

### ISSUE THREAD

**Issue by ghostsquad** [Naereen/badges#17]
this is request to add Go badges (such as godoc)

**Comment by Naereen** [comment]
Hi :smile:
I can add the following badges, would that be enough?
![Capture du 2020-07-28 19-48-21](https://user-images.githubusercontent.com/11994719/88702270-648c8e80-d10b-11ea-8c6b-95c728c5d6c1.png)
Regards

**Comment by ghostsquad** [comment]
Actually, funny enough, I was looking for the godocs badge which isn't on the shields.io website

**Comment by ghostsquad** [comment]
Here's some more info from the internets

https://github.com/nanomsg/mangos/commit/4684c4df4a2ef6598a3cbdab581df12dcc683c3d?ts=4

**Comment by Naereen** [comment]
OK. I added all these badges.
Please have a look at https://github.com/Naereen/badges/#go-related

**Comment by ghostsquad** [comment]
Awesome awesome!!!

**Comment by Naereen** [comment]
Great!
