### ISSUE TITLE
maybe add my badges

### ISSUE THREAD

**Issue by ctrl-shift-make** [Naereen/badges#22]
add my badge 
even tho its for a kid lang it works well 
[![small-basic-denotation](https://img.shields.io/badge/Made%20with-Small%20Basic-orange)](https://smallbasic-publicwebsite.azurewebsites.net/)

**Comment by Naereen** [comment]
Hi @ctrl-shift-make,
Thanks for the suggestion.
I'm afraid that this tool is not widely used by enough person, I won't add it. Sorry
