### ISSUE TITLE
how to connect discord to these badges

### ISSUE THREAD

**Issue by puppala-koushik** [Naereen/badges#23]
I want to know how to connect the discord server to the badges

**Comment by Naereen** [comment]
Hi @puppala-koushik,
I don't understand your question, could you please explain more?
Thanks, regards. @Naereen

**Comment by puppala-koushik** [comment]
Means we are getting discord server online members count how to to get it

**Comment by Naereen** [comment]
Hi again @puppala-koushik,
Well it's explained there: https://github.com/Naereen/badges#discord
For more information, see https://shields.io/, look for Discord in the search bar, and there is a small tutorial.
