### ISSUE TITLE
Bagdes with Custom Logo using Base64

### ISSUE THREAD

**Issue by GabriOliv** [Naereen/badges#27]
A suggestion...
Expand some badges with custom logo ideas using Shields.io and Base64.
Like Here:
[Gist custom_logo_shields.md](https://gist.github.com/GabriOliv/5d98d76bd5edb5d4f774b8fd0e494823)

**Comment by Naereen** [comment]
Hello there @GabriOliv,
Thanks for the suggestion. Feel free to write and submit a pull request, if it's adding something to the quality of this (tiny) project I will be glad to merge it!
Regards, @Naereen
