### ISSUE TITLE
Add the MyViewCounts View Counter

### ISSUE THREAD

**Issue by RayhanADev** [Naereen/badges#29]
It's not *quite* a badge, but a while back I made an application called **MyViewCounts**, a view counter to embed in READMEs that allows **the greatest amount of customizability** when compared with other view counters!

Here's the Website: https://myviewcounts.rayhanadev.repl.co/
Here's the Github Repo: https://github.com/RayhanADev/MyViewCounts
Here's a View Counter on my Profile: https://github.com/RayhanADev#custom-viewcounter

Let me know what you think!

**Comment by Naereen** [comment]
Hi @RayhanADev,
Thanks for the offer, but I won't accept as it's not a badge, sorry.
I also think there already is a view count badge in this repo.
Regards!

**Comment by RayhanADev** [comment]
Okay thanks!
