### ISSUE TITLE
Request for mailing list badge

### ISSUE THREAD

**Issue by mwpowellhtx** [Naereen/badges#3]
Do you happen to know if there is one? For mailing lists? Or even Google groups?

**Comment by Naereen** [comment]
Hi,
No I never seen any for either mailing lists or Google groups.

But this would be easy to do, using https://shields.io/ generic API:
[![Generic badge](https://img.shields.io/badge/<SUBJECT>-<STATUS>-<COLOR>.svg)](https://shields.io/)
```markdown
[![Generic badge](https://img.shields.io/badge/<SUBJECT>-<STATUS>-<COLOR>.svg)](https://shields.io/)
```

### For mailing lists
[![Mailing list : test](https://img.shields.io/badge/Mailing%20list-Test-orange.svg)](https://some-home-page.com/for/this/mailing/list/)
```markdown
[![Mailing list : test](https://img.shields.io/badge/Mailing%20list-Test-orange.svg)](https://some-home-page.com/for/this/mailing/list/)
```

### For Google groups
[![Google group : SSFAM News](https://img.shields.io/badge/Google%20Group-SSFAM%20News-blue.svg)](https://groups.google.com/forum/#!forum/ssfam-news)
```markdown
[![Google group : SSFAM News](https://img.shields.io/badge/Google%20Group-SSFAM%20News-blue.svg)](https://groups.google.com/forum/#!forum/ssfam-news)
```

Please modify as you wish.
