### ISSUE TITLE
Badge suggestions

### ISSUE THREAD

**Issue by yuri-norwood** [Naereen/badges#37]
I'm a big fan of adding badges to my READMEs, I'd like to humbly offer my collection so far.

# Icons

These use [shields.io](shields.io) with the `logo` paramater set to any logo supported by [simple icons](https://github.com/simple-icons/simple-icons), and no label or text. There are hundreds of logos available but these are some that I've found useful.

* [![Vim](https://img.shields.io/badge/--019733?logo=vim)](https://www.vim.org/)
  ```markdown
  [![Vim](https://img.shields.io/badge/--019733?logo=vim)](https://www.vim.org/)
  ```
* [![OpenBSD](https://img.shields.io/badge/--F2CA30?logo=openbsd&logoColor=000000)](https://www.openbsd.org/)
  ```markdown
  [![OpenBSD](https://img.shields.io/badge/--F2CA30?logo=openbsd&logoColor=000000)](https://www.openbsd.org/)
  ```
* [![Suckless](https://img.shields.io/badge/--1177AA?logo=suckless)](https://suckless.org/)
  ```markdown
  [![Suckless](https://img.shields.io/badge/--1177AA?logo=suckless)](https://suckless.org/)
  ```
* [![dwm](https://img.shields.io/badge/--1177AA?logo=dwm)](https://dwm.suckless.org/)
  ```markdown
  [![dwm](https://img.shields.io/badge/--1177AA?logo=dwm)](https://dwm.suckless.org/)
  ```
* [![git](https://img.shields.io/badge/--F05032?logo=git&logoColor=ffffff)](http://git-scm.com/)
  ```markdown
  [![git](https://img.shields.io/badge/--F05032?logo=git&logoColor=ffffff)](http://git-scm.com/)
  ```
* [![x11](https://img.shields.io/badge/--F28834?logo=x.org&logoColor=ffffff)](https://x.org/)
  ```markdown
  [![x11](https://img.shields.io/badge/--F28834?logo=x.org&logoColor=ffffff)](https://x.org/)
  ```
* [![Visual Studio](https://img.shields.io/badge/--6C33AF?logo=visual%20studio)](https://visualstudio.microsoft.com/)
  ```markdown
  [![Visual Studio](https://img.shields.io/badge/--6C33AF?logo=visual%20studio)](https://visualstudio.microsoft.com/)
  ```
* [![Go](https://img.shields.io/badge/--00ADD8?logo=go&logoColor=ffffff)](https://golang.org/)
  ```markdown
  [![Go](https://img.shields.io/badge/--00ADD8?logo=go&logoColor=ffffff)](https://golang.org/)
  ```

# License Badges

* Unlicense (i.e. public domain)
  * [![Unlicense](https://img.shields.io/badge/License-Unlicense-blue.svg)](https://unlicense.org/)
    ```markdown
    [![Unlicense](https://img.shields.io/badge/License-Unlicense-blue.svg)](https://unlicense.org/)
    ```
  * [![Unlicense](https://licensebuttons.net/p/88x31.png)](https://unlicense.org/)
    ```markdown
    [![Unlicense](https://licensebuttons.net/p/88x31.png)](https://unlicense.org/)
    ```
* *Note: https://licensebuttons.net is a great resource for many other licenses, it could be good to link to it as part of the license section?*

  For example, it allows customizing the colours of the badges:
  * [![Attribution-NonCommercial-ShareAlike](https://licensebuttons.net/i/l/by-nc-sa/ffffff/00/00/00/88x31.png)](https://creativecommons.org/licenses/by-nc-sa/2.0/)
    ```markdown
    [![Attribution-NonCommercial-ShareAlike](https://licensebuttons.net/i/l/by-nc-sa/ffffff/00/00/00/88x31.png)](https://creativecommons.org/licenses/by-nc-sa/2.0/)
    ```
  * [![Attribution-NonCommercial-ShareAlike](https://licensebuttons.net/i/l/by-nc-sa/000000/ff/ff/ff/88x31.png)](https://creativecommons.org/licenses/by-nc-sa/2.0/)
    ```markdown
    [![Attribution-NonCommercial-ShareAlike](https://licensebuttons.net/i/l/by-nc-sa/000000/ff/ff/ff/88x31.png)](https://creativecommons.org/licenses/by-nc-sa/2.0/)
    ```
  * [![Attribution-NonCommercial-ShareAlike](https://licensebuttons.net/i/l/by-nc-sa/eeeeee/ff/00/ff/88x31.png)](https://creativecommons.org/licenses/by-nc-sa/2.0/)
    ```markdown
    [![Attribution-NonCommercial-ShareAlike](https://licensebuttons.net/i/l/by-nc-sa/eeeeee/ff/00/ff/88x31.png)](https://creativecommons.org/licenses/by-nc-sa/2.0/)
    ```

# JSDelivr

[JSDelivr](https://www.jsdelivr.com/) is a CDN for JavaScript, it is one of the few that allow using GitHub repos with zero setup, just put the username and repo in the URL and boom, done.

* [![JSDelivr CDN](https://data.jsdelivr.com/v1/package/gh/yuri-norwood/JAprilFools/badge?style=rounded)](https://www.jsdelivr.com/package/gh/yuri-norwood/JAprilFools)
  ```markdown
  [![JSDelivr CDN](https://data.jsdelivr.com/v1/package/gh/yuri-norwood/JAprilFools/badge?style=rounded)](https://www.jsdelivr.com/package/gh/yuri-norwood/JAprilFools)
  ```
* [![jsDelivr CDN](https://img.shields.io/jsdelivr/gh/hm/yuri-norwood/JAprilFools)](https://www.jsdelivr.com/package/gh/yuri-norwood/JAprilFools)
  ```markdown
  [![jsDelivr CDN](https://img.shields.io/jsdelivr/gh/hm/yuri-norwood/JAprilFools)](https://www.jsdelivr.com/package/gh/yuri-norwood/JAprilFools)
  ```

**Comment by Naereen** [comment]
Hello there,
I accept all these, please open a pull request :+1: !

**Comment by yuri-norwood** [comment]
Please see #39
