### ISSUE TITLE
Add saythanks.io

### ISSUE THREAD

**Issue by u2berggeist** [Naereen/badges#4]
I think adding [saythanks.io](https://github.com/kennethreitz/saythanks.io) would be a great thing to get more awareness of out there!

**Comment by Naereen** [comment]
Thanks for your suggestion, I will add badges to saythanks.io as soon as possible. Or you can submit a PR.

**Comment by Naereen** [comment]
Should be ok, please check https://github.com/Naereen/badges#say-thanks

**Comment by u2berggeist** [comment]
Awesome! Thanks for the quick update!

**Comment by u2berggeist** [comment]
Awesome! Thanks for the quick update!
