### ISSUE TITLE
Badge suggestion

### ISSUE THREAD

**Issue by edoardottt** [Naereen/badges#40]
Hi! 

I would like to propose new badges strictly related to Operating Systems.  
Like:  

- [ ] Linux-like
- [ ] Windows
- [ ] macOS

**Comment by Naereen** [comment]
Hello there,
Thanks for the suggestions, yes such badges could be useful.
Feel free to add them in a pull request, I'll merge it.

You can take the badges from https://shields.io/category/platform-support or design them, for instance using the generic badge of https://shields.io/.
Regards.

**Comment by edoardottt** [comment]
I will try, anyway I think shields.io uses [pybadges](https://github.com/google/pybadges).

**Comment by edoardottt** [comment]
Any update??

**Comment by edoardottt** [comment]
Merged
