### ISSUE TITLE
Add badges from the https://badgen.net/ website?

### ISSUE THREAD

**Issue by Naereen** [Naereen/badges#5]

**Comment by Naereen** [comment]
> :fr: J'ai un peu la flemme, il y en a tellement sur ce (tout nouveau) site…

**Comment by rahulvigneswaran** [comment]
You can make any customized badges from [shields.io](https://shields.io/#/examples/dependencies).

**Comment by Naereen** [comment]
@rahulvigneswaran I know, it's the first example given on the page: https://github.com/Naereen/badges#generic

But such badge is just a static image, the goal of the all the other badges is to be dynamically generated, by fetching real-time data (e.g., number of stars of a project on GitHub: [![GitHub stars](https://img.shields.io/github/stars/Naereen/badges.svg?style=social&label=Star&maxAge=2592000)](https://GitHub.com/Naereen/badges/stargazers/))

**Comment by FuegoBoss** [comment]
#33

**Comment by Naereen** [comment]
Hi, I merged #33 as requested.

**Comment by Naereen** [comment]
Closed in #44
