### ISSUE TITLE
Badge Reference Table

### ISSUE THREAD

**Issue by kaustav202** [Naereen/badges#53]
The repo has a lot of badges ..it would be helpful if a quick reference table is added linking to specific badge section in the README for quick lookup and search.

**Comment by Naereen** [comment]
Hello @kaustav202 and thanks for your interest.
In the first paragraph of the README there is a collapsible table of content, which already does what you ask!
Here have a look at this very quick GIF demo:
![Peek 28-02-2022 20-10](https://user-images.githubusercontent.com/11994719/156043991-9595fee2-439a-4040-aef1-c8138ac62b40.gif)
Closing this.
Regards. @Naereen

**Comment by kaustav202** [comment]
Sure ..I didn't pay attention.
