### ISSUE TITLE
Website up/down with domain-name

### ISSUE THREAD

**Issue by anionDev** [Naereen/badges#57]
The usual Website up/down badge markdown-content looks like

```
[![example.com](https://img.shields.io/website-up-down-green-red/https/example.com.svg)](https://example.com/)
```

which results in:
![image](https://user-images.githubusercontent.com/19505692/170861930-8a99e515-b6ff-480f-83b4-e9347e17512f.png)

This is nice but not ideal when you use this badge multiple times (with different domains): You do not know which website is up and which is down (except you hover over it to see the link).

It seems that the text in the square-brackets at the beginning does not have any effect. The left text in the badge is always `website`.

So: Is the text `website` customizable? It would be nice if we are at least able to set the domain-name as text for the left part to have a badge-text like "example.com | up".

**Comment by Naereen** [comment]
Hello there @anionDev,
Thanks for your question.
Using `shields.io` badges, it seems impossible to do what you are looking for:
![Capture d’écran de 2022-05-29 11-57-49](https://user-images.githubusercontent.com/11994719/170862413-6ce8ea8c-a67a-43ba-b63f-8b2e6753c7c7.png)
See documentation online at <https://shields.io/category/monitoring>.
Regards.

**Comment by anionDev** [comment]
Ok. Anyway, thank you for your answer!
