### ISSUE TITLE
Clones

### ISSUE THREAD

**Issue by diegohce** [Naereen/badges#6]
Is there any badge for displaying how many times a repo has been cloned?

Thanks you!

**Comment by Naereen** [comment]
Hi @diegohce!
I never seen any… but shields.io has added *a lot* of badges, and yes it's now possible! See https://shields.io/#/examples/social for more examples:

- Stars:
![GitHub stars](https://img.shields.io/github/stars/Naereen/badges.svg?style=social&label=Stars)

- Forks:
![GitHub forks](https://img.shields.io/github/forks/Naereen/badges.svg?style=social&label=Forks)

- Downloads:
![GitHub downloads](https://img.shields.io/github/downloads/Naereen/badges/total.svg?style=social&label=Downloads)

But I think GitHub does not give the number of clones in its API.
Sorry!

**Comment by diegohce** [comment]
Sorry to post on al closed issue. Just to let you know, they do [Clones](https://developer.github.com/v3/repos/traffic/#clones)

Cheers!

**Comment by Naereen** [comment]
Oh that's interesting, thanks!
I haven't seen badges supporting this, but maybe we can hack it with the "dynamic" badge system provided by either [`shields.io`](https://shields.io/) or [`badgen.net`](https://badgen.net/)?

**Comment by Naereen** [comment]
Indeed it works:
```bash
$ curl -u Naereen https://api.github.com/repos/Naereen/badges/traffic/clones
Enter host password for user 'Naereen':
{
  "count": 1,
  "uniques": 1,
  "clones": [
    {
      "timestamp": "2018-09-26T00:00:00Z",
      "count": 1,
      "uniques": 1
    }
  ]
}
```

**Comment by Naereen** [comment]
But these API endpoints require to have push access to the repository…
So there is no hope on using a safe external badge generator to display clone statistics (in my honest opinion).

**Comment by diegohce** [comment]
That's what I thought.
