### ISSUE TITLE
Typo in the last commit

### ISSUE THREAD

**Issue by VokunGahrotLaas** [Naereen/badges#66]
This line: https://github.com/Naereen/badges/blob/3f377c4c0a2a59913384d96f7fd48e065b0e87f4/README.md?plain=1#L695C6-L695C6 and the line below,
Incorrectly point to https://github.com/Naereen1/github-readme-streak-stats when they should really go to https://github.com/DenverCoder1/github-readme-streak-stats.

**Comment by Naereen** [comment]
HI @VokunGahrotLaas, thanks for the issue, it's been fixed.
